### ISSUE TITLE
GL/glut.h header file is missing

### ISSUE THREAD

**Issue by paradoxnafi** [NSU-ACM-SC/BD-Flag-OpenGL#1]
I have tried to compile your code but `GL/glut.h` is missing. 
```
g++     main.cpp   -o main
main.cpp:12:10: fatal error: GL/glut.h: No such file or directory
 #include <GL/glut.h>
          ^~~~~~~~~~~
compilation terminated.
<builtin>: recipe for target 'main' failed
make: *** [main] Error 1

```
Please upload the header file.

**Comment by shawonashraf** [comment]
Just the header file won’t do. You need to have a port of OpenGL installed on your machine. And since frameworks are in play, use the cmake config mentioned in the README to to build. 😊

Note: if you’re on macOS, just include OpenGL and GLUT from Xcode. They’re shipped with the OS. If you’re on a Linux Distro, check which OpenGL port your Distro supports. On Windows, GLFW/ GLEW will do. Or Using age old FreeGLUT will do.

And a note though, Do read the README's of repositories. 

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
